### ISSUE TITLE
Consider publishing on Open VSX

### ISSUE THREAD

**Issue by C-512L** [dreamcatcher45/podmanager#1]
[Open VSX](https://open-vsx.org/) is an Eclipse open-source project and alternative to the Visual Studio Marketplace. It's used by default by other VSCode-based IDEs and editors such as VSCodium or Theia IDE.

**Comment by dreamcatcher45** [comment]
Sure...I will publish it soon..Thanks for letting me know😃

**Comment by dreamcatcher45** [comment]
> [Open VSX](https://open-vsx.org/) is an Eclipse open-source project and alternative to the Visual Studio Marketplace. It's used by default by other VSCode-based IDEs and editors such as VSCodium or Theia IDE.

I published the extension in Open VSX..here is the link
https://open-vsx.org/extension/dreamcatcher45/podmanager
