### ISSUE TITLE
Ability to view pod logs

### ISSUE THREAD

**Issue by franchyze923** [dreamcatcher45/podmanager#11]
I'm used to using the Docker extension which has a very useful feature that allows the user to view pod logs. Can the ability to view pod logs be implemented? 

<img width="307" alt="image" src="https://github.com/user-attachments/assets/d2a7d8cf-fcce-420d-83e6-f11985765e02">

**Comment by dreamcatcher45** [comment]
@franchyze923 Sure 😃,It will be added in the next update...

**Comment by dreamcatcher45** [comment]
@franchyze923  The log view option is added to v2.0.4 .Thanks😃
