### ISSUE TITLE
Feature Request: podman push <image>

### ISSUE THREAD

**Issue by swheettaos** [dreamcatcher45/podmanager#13]
It would be great if one of the things you could do is "push" I can delete and do other stuff, but if I want to push I have to do it with the CLI.  I know the push would only work if I did the podman login <container repository> first .. but I only need to do that once.  

Unless I'm missing this somewhere.. this would be great.  I love the plugin!

**Comment by dreamcatcher45** [comment]
@swheettaos Thanks for the suggestion! I'll make sure to include it in the upcoming update👍👍

**Comment by dreamcatcher45** [comment]
@swheettaos The `push image` feature is added to `v2.0.6`  Its disabled by default, you need to enable it in the settings. Do check it out...Sorry for being late for this update.

**Comment by swheettaos** [comment]
Tested. Works like a champ!  Thanks!
