### ISSUE TITLE
Compose (V2)

### ISSUE THREAD

**Issue by theseeker58** [dreamcatcher45/podmanager#2]
Hello,
first of all, great job! A suggestion more than a issue. It would be nice to have context menus on compose yaml files to execute up, down, start and stop. And possibly in the container list the aggregation project if compose had been used.
Cheers

**Comment by dreamcatcher45** [comment]
Thank you for the suggestion 😊...I will try to get this done soon🤝

**Comment by dreamcatcher45** [comment]
> Hello, first of all, great job! A suggestion more than a issue. It would be nice to have context menus on compose yaml files to execute up, down, start and stop. And possibly in the container list the aggregation project if compose had been used. Cheers

The requested option for managing `compose ` is added to the latest version(v0.0.5) and is updated in vscode marketplace.🤝
Please check it out and thank for the suggestion😄

**Comment by theseeker58** [comment]
Hi @dreamcatcher45 
selecting up I get an error "No compose file found in the current directory", even though the file is there

![Screenshot from 2024-08-24 05-48-45](https://github.com/user-attachments/assets/ab541c4e-24ed-4fda-bc8e-531698a915fe)

Consider also that you could have more than one compose file in a project. I meant a context menu after selecting the compose file. Something like available in the docker extension from Microsoft that unfortunately is stuck to the 1.22.2 release for Podman. Possibly I wasn't clear when suggesting. I mean something like this

![Screenshot from 2024-08-24 05-43-26](https://github.com/user-attachments/assets/7bf99c97-eefd-4f08-b0f1-fe5b98398045)

And when the containers are started (or just up even if stopped) a context menu on the project name for the actions. Something like this

![Screenshot from 2024-08-24 05-46-06](https://github.com/user-attachments/assets/ed23900b-1074-49ab-afd5-619c1925e4d3)

You can take a look to the Docker extension from Microsoft.

Cheers  mate

**Comment by dreamcatcher45** [comment]
> Hi @dreamcatcher45 
> selecting up I get an error "No compose file found in the current directory", even though the file is there
> 
> ![Screenshot from 2024-08-24 05-48-45](https://github.com/user-attachments/assets/ab541c4e-24ed-4fda-bc8e-531698a915fe)
> 
> Consider also that you could have more than one compose file in a project. I meant a context menu after selecting the compose file. Something like available in the docker extension from Microsoft that unfortunately is stuck to the 1.22.2 release for Podman. Possibly I wasn't clear when suggesting. I mean something like this
> 
> ![Screenshot from 2024-08-24 05-43-26](https://github.com/user-attachments/assets/7bf99c97-eefd-4f08-b0f1-fe5b98398045)
> 
> And when the containers are started (or just up even if stopped) a context menu on the project name for the actions. Something like this
> 
> ![Screenshot from 2024-08-24 05-46-06](https://github.com/user-attachments/assets/ed23900b-1074-49ab-afd5-619c1925e4d3)
> 
> You can take a look to the Docker extension from Microsoft.
> 
> Cheers  mate

Ok..I see..Try renaming the compose file to docker-compose.yaml...It worked for me...I will add other formats and context menus to next update soon🤝🤝

**Comment by dreamcatcher45** [comment]
> Hi @dreamcatcher45 selecting up I get an error "No compose file found in the current directory", even though the file is there
> 
> ![Screenshot from 2024-08-24 05-48-45](https://private-user-images.githubusercontent.com/65131747/361100245-ab541c4e-24ed-4fda-bc8e-531698a915fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1OTA0MDYsIm5iZiI6MTcyNDU5MDEwNiwicGF0aCI6Ii82NTEzMTc0Ny8zNjExMDAyNDUtYWI1NDFjNGUtMjRlZC00ZmRhLWJjOGUtNTMxNjk4YTkxNWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDEyNDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjMThkM2FmNjNjZmViYjBjZDkxMTU2Y2VhN2Q0NTI3NzJkZGE1ZGIwYjIyY2E1YzJlNTM4ZDk4YTFlMDE5OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Iltrg_RfioU9FYln3XLMN6JN3uj-1ctlPKexjIOYeak)
> 
> Consider also that you could have more than one compose file in a project. I meant a context menu after selecting the compose file. Something like available in the docker extension from Microsoft that unfortunately is stuck to the 1.22.2 release for Podman. Possibly I wasn't clear when suggesting. I mean something like this
> 
> ![Screenshot from 2024-08-24 05-43-26](https://private-user-images.githubusercontent.com/65131747/361100530-7bf99c97-eefd-4f08-b0f1-fe5b98398045.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1OTA0MDYsIm5iZiI6MTcyNDU5MDEwNiwicGF0aCI6Ii82NTEzMTc0Ny8zNjExMDA1MzAtN2JmOTljOTctZWVmZC00ZjA4LWIwZjEtZmU1Yjk4Mzk4MDQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDEyNDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ZmVkMjg3MzZmZmJjMjc1MDA4ZDU3YjQyYTNhZWU0NWNhMDNjYzk4ODdmM2U5YTBlNDRjNDhiMjdkMTg4MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XW6p_ZgHYRu348_1OHvw9KVi4KVhoi9lA9Y0LggnIYU)
> 
> And when the containers are started (or just up even if stopped) a context menu on the project name for the actions. Something like this
> 
> ![Screenshot from 2024-08-24 05-46-06](https://private-user-images.githubusercontent.com/65131747/361100641-ed23900b-1074-49ab-afd5-619c1925e4d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1OTA0MDYsIm5iZiI6MTcyNDU5MDEwNiwicGF0aCI6Ii82NTEzMTc0Ny8zNjExMDA2NDEtZWQyMzkwMGItMTA3NC00OWFiLWFmZDUtNjE5YzE5MjVlNGQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDEyNDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1Yzk0OGI3ZWFlNzNhOTIwNzk2NzFiMmM3NDkzYjNiMzA2ZDgzMTMwM2M2MTM5YWRmZGIyMTI4ZTY0YTJiZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QfOUiNmYZEcLvtunHRVJ1IrDqAmF8MVS0lY3EhvX22k)
> 
> You can take a look to the Docker extension from Microsoft.
> 
> Cheers mate

i have added compose up option in context menu for .yaml and yml files...also a compose group section in the container section with other compose options⚙️...Check out the latest update of the extension(0.0.6)😇
