### ISSUE TITLE
Error occurs: "Element with id 702ed6eaf2af is already registered"

### ISSUE THREAD

**Issue by taomanwai** [dreamcatcher45/podmanager#3]
It happens when refresh containers and images in Pod Manager tab. Could you take a look? Thanks.

Versions:
Pod Manager v0.0.6
VSCode v1.92.1 (user setup)

**Comment by dreamcatcher45** [comment]
> It happens when refresh containers and images in Pod Manager tab. Could you take a look? Thanks.
> 
> Versions:
> Pod Manager v0.0.6
> VSCode v1.92.1 (user setup)

Can you please provide more details on the issue...is it when you use `compose up` or is it on regular containers

**Comment by taomanwai** [comment]
Any more information I should give you? It is on regular containers.

**Comment by dreamcatcher45** [comment]
> Any more information I should give you? It is on regular containers.

@taomanwai ok I will check it and find a fix 😊

**Comment by dreamcatcher45** [comment]
@taomanwai I checked the issue and its not caused by the extension's code...its some issue related to the container...Please check it out in the web...Thank you for reaching out😄👍

**Comment by dreamcatcher45** [comment]
> Reason behind the issue found:
> 
> ![image](https://github.com/user-attachments/assets/9b121b90-2a68-40f5-9842-2f2957af848e)
> Within podman images, I have multiple repo:tag sharing with the same image id, and it causes the issue.
> 
> Would you consider making pod manager supporting the above scenario? Thanks for consideration.

@taomanwai Ok,I see...I will add this to the upcoming update soon🤝

**Comment by taomanwai** [comment]
Thank you for your prompt response, previous hard work, and the upcoming update! 🙏🏻

**Comment by dreamcatcher45** [comment]
@taomanwai I have fixed the issue👍 and its added to the latest version (0.0.8)..Please check it out...Thanks🤝

**Comment by taomanwai** [comment]
@dreamcatcher45 Checked, it works, thanks a lot!
