### ISSUE TITLE
Multiple references to an image causes the image list to not display any images

### ISSUE THREAD

**Issue by NothingTooSerious** [dreamcatcher45/podmanager#4]
# Problem
The same image id can occur when referenced in multiple repositories causing no images to display.

I saw a similar issue had been raised a few days earlier, the info below may assist in producing a fix.

# Reproduce

* Create a duplicate image reference.

~~~
podman image pull mcr.microsoft.com/vscode/devcontainers/cpp:debian-11
podman image pull mcr.microsoft.com/devcontainers/cpp:debian-11
podman image list
REPOSITORY                                         TAG         IMAGE ID      CREATED       SIZE
mcr.microsoft.com/devcontainers/cpp                debian-11   c9d01d43d7b0  8 days ago    1.88 GB
mcr.microsoft.com/vscode/devcontainers/cpp         debian-11   c9d01d43d7b0  8 days ago    1.88 GB
~~~

* Click on PODMANAGER -> Images

Plugin will give following error when listing images

~~~
Element with id c9d01d43d7b0 is already registered
~~~

# Cause
VSCode tree item must have an ID that is unique across the tree. However, image IDs are not unique. The plugin data model for storing and translation between image IDs and tree item IDs assumes a 1:1 relationship. This is unfortunately false. The plugin data model must take account of the 1:N relationships.

Below is an example workaround of the issue, but does not address the underlying cause, being the data model is broken. An artefact of the workaround is only the first repository reference to the duplicate image is displayed.   

~~~
--- extension.js.orig	2024-08-30 06:56:04.388000000 +1000
+++ extension.js	2024-08-30 07:32:08.276000000 +1000
@@ -319,12 +319,20 @@
     async getImages() {
         try {
             const { stdout } = await execAsync('podman image ls --format "{{.ID}}|{{.Repository}}:{{.Tag}}"');
-            return stdout.split('\n')
-                .filter(line => line.trim() !== '')
-                .map(line => {
-                const [id, name] = line.split('|');
-                return new PodmanItem(`${name} (${id})`, vscode.TreeItemCollapsibleState.None, 'image', id);
+            const items = stdout.split('\n')
+                          .filter(line => line.trim() !== '')
+                          .map(line => {
+                              const [id, name] = line.split('|');
+                              return new PodmanItem(`${name} (${id})`, vscode.TreeItemCollapsibleState.None, 'image', id);
+                          });
+            // Remove duplicate id entries
+            // Only shows the first image repository - tag -id of duplicate id's. Needs fix.
+            let seen = new Set();
+            const reditems = items.filter(item => {
+                let k = item.id;
+                return seen.has(k) ? false : seen.add(k);
             });
+            return reditems;
         }
         catch (error) {
             vscode.window.showErrorMessage('Failed to get images: ' + error);
~~~

# Other
Thanks for writing the extension. It is useful.

**Comment by dreamcatcher45** [comment]
@NothingTooSerious Thank you for the detailed explanation..I was trying to find the solution for the issue these days...This helps a lot🥰.I will soon fix the issue 🤝

**Comment by dreamcatcher45** [comment]
@NothingTooSerious I have fixed the issue👍 and its added to the latest version (0.0.8)..Please check it out...Thanks🤝

**Comment by NothingTooSerious** [comment]
Looks good 👍
