### ISSUE TITLE
Feature Requests - stats & pruning

### ISSUE THREAD

**Issue by NothingTooSerious** [dreamcatcher45/podmanager#5]
Hi,
Some useful features to consider integrating into this plugin.

# Podman disk stats
A very useful ability is seeing podman disk size usage presented in the GUI as some stats.

Maybe as a stats section after the tree section?

Why is this useful, podman disk usage includes overlays (or stacked if using VFS) as separate counts giving a true representation of consumed size, not just actual disk usage. Handy when using overlays and yet wanting to see disk consumption impacts for those living with VFS, or seeing container leaking over time, or just needing to claw back disk space.

As the system call is expensive, perform once asynchronously on startup and maybe once every hour or on explicit demand. Separate to normal refresh.

~~~
> podman system df
TYPE           TOTAL       ACTIVE      SIZE        RECLAIMABLE
Images         28          2           42.61GB     39.42GB (93%)
Containers     2           0           2.097GB     2.097GB (100%)
Local Volumes  1           2           364.1MB     0B (0%)
~~~

# Podman container stats

See container resource usage in a similar manner to disk stats. Useful for container development and packaging and understanding resource consumption. Bonus points if over time graphing is available.

~~~
> podman stats -a --no-stream
ID            NAME           CPU %       MEM USAGE / LIMIT  MEM %       NET IO       BLOCK IO    PIDS        CPU TIME    AVG CPU %
1baa6a2d3bef  cool_goldberg  0.12%       204.8kB / 4.105GB  0.00%       430B / 110B  0B / 0B     3           613.006ms   0.12%
745878eb12e4  reverent_jang  0.12%       213kB / 4.105GB    0.01%       430B / 220B  0B / 0B     3           617.938ms   0.12%
~~~

# Ability to prune
Podman / Docker does not clean up after itself. Having ability to do house keeping is nice. Especially when seeing disk stats grow!

* Remove all images not associated to containers (dangling):   podman image prune -f
* Remove all images not in use by containers (unused and dangling): podman image prune -a -f
* Remove podman building cache: podman builder prune -a -f

# Show all images
Have a new separate tree arm that lists all images (includes dangling and unused) or every image but used to complement the existing image arm. Example below shows all images. Explains why reclaimable images percentage is so high and disk space disappearing (especially for those using VFS). Using a separate arm or separate display to normal images reduces noise.

~~~
> podman image list -a
REPOSITORY                                                                                  TAG         IMAGE ID      CREATED      SIZE
localhost/vsc-fgtlint-8fda9119732bb8ec300cf3b85c265d4f998531c1a72ec8b8abe8b920b5a49c38-uid  latest      5b985f37b68d  2 days ago   1.6 GB
<none>                                                                                      <none>      88eeafb0e5bd  2 days ago   1.6 GB
<none>                                                                                      <none>      7714ca47bda1  2 days ago   1.6 GB
<none>                                                                                      <none>      7cd451bf8385  2 days ago   1.6 GB
<none>                                                                                      <none>      65f7f8d0847e  2 days ago   1.6 GB
<none>                                                                                      <none>      d66f004d8377  2 days ago   1.6 GB
<none>                                                                                      <none>      a9cbfec9d055  2 days ago   1.6 GB
<none>                                                                                      <none>      7e5db97c6188  2 days ago   1.6 GB
localhost/vsc-fgtlint-8fda9119732bb8ec300cf3b85c265d4f998531c1a72ec8b8abe8b920b5a49c38      latest      c507893ba791  2 days ago   1.6 GB
localhost/vsc-gatus-c8c17f4cfe5f8c84b924659c4dc01e53f7d29686fdfc31554167fd57774a4d7d-uid    latest      21f72f45d592  2 days ago   1.6 GB
<none>                                                                                      <none>      f3555827d62a  2 days ago   1.6 GB
<none>                                                                                      <none>      52c360a7fd18  2 days ago   1.6 GB
<none>                                                                                      <none>      e76bfebafe97  2 days ago   1.6 GB
<none>                                                                                      <none>      054b5f9a0000  2 days ago   1.6 GB
<none>                                                                                      <none>      86dee9ee395c  2 days ago   1.6 GB
<none>                                                                                      <none>      771f31edf1c1  2 days ago   1.6 GB
<none>                                                                                      <none>      96f6f6d9e6ea  2 days ago   1.6 GB
localhost/vsc-gatus-c8c17f4cfe5f8c84b924659c4dc01e53f7d29686fdfc31554167fd57774a4d7d        latest      7c524681c86b  2 days ago   1.6 GB
<none>                                                                                      <none>      35332a1996b4  2 days ago   1.6 GB
<none>                                                                                      <none>      6b33fd6394dd  2 days ago   1.54 GB
<none>                                                                                      <none>      b7bb890de10d  2 days ago   1.54 GB
<none>                                                                                      <none>      ad008383e5fb  2 days ago   1.54 GB
<none>                                                                                      <none>      9da399370b3d  2 days ago   1.54 GB
<none>                                                                                      <none>      2b43342bd06a  2 days ago   1.54 GB
<none>                                                                                      <none>      440fbe4e6010  2 days ago   1.54 GB
mcr.microsoft.com/devcontainers/go                                                          1-bullseye  fed459442993  9 days ago   1.54 GB
mcr.microsoft.com/vscode/devcontainers/go                                                   1-bullseye  fed459442993  9 days ago   1.54 GB
docker.io/library/alpine                                                                    latest      324bc02ae123  5 weeks ago  8.09 MB
~~~

**Comment by dreamcatcher45** [comment]
@NothingTooSerious ok...I will add these in later updates🤝

**Comment by NothingTooSerious** [comment]
The colour indicator works well! Immediate visual impact of what is and isn't required.

Overview info is great. Just having that info in the same place saves time and increases awareness. Only nit-pick is the formatting is off, but that is a very minor visual impact and is because of being part of a tree element rather than a table element. 

Very cool to have this now available!

Looks like the `podman stats` command has unmet requirements. Cgroup V2 is needed where podman is running for stats to work. This is documented in [podman stats man page](https://docs.podman.io/en/latest/markdown/podman-stats.1.html). Looks like it is a feature that relies on the server being configured correctly.

Regardless of the extension, be interesting to know why your podman and cgroups v2 is broken.

**Comment by dreamcatcher45** [comment]
@NothingTooSerious Thanks😊...I am not sure why is the stats not working..I am trying to find it out😊

**Comment by NothingTooSerious** [comment]
Nicely done. Thank you.
