### ISSUE TITLE
Error installing extension on version 1.80.1

### ISSUE THREAD

**Issue by TorstenC** [dreamcatcher45/podmanager#6]
I tried to install the extension via a remote tunnel and in the WSL:

```bash
$ code --install-extension dreamcatcher45.podmanager
```

In both cases I got:

> Can't install 'dreamcatcher45.podmanager' extension because it is not compatible
> with the current version of Visual Studio Code (version 1.80.1).

**Comment by dreamcatcher45** [comment]
@TorstenC ..This extension is built on     ` "vscode": "^1.92.0" `.There is no version of this extension that works on the mentioned vscode version...I am sorry to say I can't  help😥😥
