### ISSUE TITLE
Attach to VS Code Feature Request

### ISSUE THREAD

**Issue by mylesmc123** [dreamcatcher45/podmanager#7]
I was having trouble connecting the Docker Extension to my Podman installation on a remote Linux server while in VS Code locally on a Mac. I came across Pod Manager from this discussion on how to setup Podman to work with the Docker VS Code extension: https://github.com/containers/podman/issues/17306

One of the workflows I use with the Docker VS Code extension is to attach the container to a VS Code instance such that the running container's file system is visible from within the VS Code UI

![image](https://github.com/user-attachments/assets/de8a98c7-2fc3-4471-ba25-85501f4810af)

This allows me to easily view files in VS Code with tabs and is really useful for debugging by seeing realtime changes to log files for things like Tomcat and other web servers; as well as easily make changes, save them, and push them to Github with the comfy VS Code UI

Is this a feature that may be available and unknown to me, or potentially in a future Pod Manager release?

**Comment by dreamcatcher45** [comment]
@mylesmc123 I will try to add this to the next update😊

**Comment by dreamcatcher45** [comment]
@mylesmc123 Hi,I tried to implement this feature..But I was not able to find a good way to implement this...I am sry

**Comment by mylesmc123** [comment]
@dreamcatcher45 No worries at all. I appreciate your software, and you putting the `help wanted` tag on this.

I believe my issue with using the Vs Code Docker extension with Podman is due to not having installed the podman-docker package along side Podman on the Linux server I'm using. 

I don't have root to test this immediately, but perhaps the Podman Manager extension would also benefit from leveraging the Docker CLI as podman-docker allows.

**Comment by mylesmc123** [comment]
Just FYI, In case any one ends up here with issues hooking up VS Code to a podman container. I was able to use the VS Code extension - Dev Containers and change the docker path to `podman` from the extensions.

![image](https://github.com/user-attachments/assets/47f33bf6-7d2a-485d-bec0-1cc44f9ae464)

Then, use the Remote Explorer tab in VS Code to attach the Podman container to VS Code.

![image](https://github.com/user-attachments/assets/d5a377eb-c88c-43b8-8000-b18beb48ba2c)
