### ISSUE TITLE
Provide settings to override podman path

### ISSUE THREAD

**Issue by bootrecords** [dreamcatcher45/podmanager#9]
Analogously to the Docker or devcontainer expansions, it's probably a good idea to allow users to override the path used by the extension to access `podman`.

In my case I'm running the flatpak version of VS Code, within which I've set up access to podman [like this](https://discussion.fedoraproject.org/t/vscode-devcontainers/45874/7), so I'm normally overwriting docker paths with `/var/home/[username]/.local/bin/podman-host`. I can also access `podman` just fine from the command line, but it's due to a shell override to pipe commands through [`host-spawn`](https://github.com/1player/host-spawn) on VS Code's integrated terminal, but that override may not be used by the pod manager extension, as to me it complains about not finding the podman executable.

**Comment by dreamcatcher45** [comment]
@bootrecords Hi, I have added this option to the latest release [here](https://github.com/dreamcatcher45/podmanager/releases/tag/v0.1.7) Please check it out and let me know if its working for you...Then I will update it to the `vscode marketplace`...It works fine in my vscode instance but I need to know if its working in the environment you mentioned..Please provide feedback after trying this release🤝

**Comment by bootrecords** [comment]
Yes, it worked! Thanks for the quick response :)

**Comment by dreamcatcher45** [comment]
@bootrecords Great🎉 I will add this release to vscode marketplace🤝
